# Generated by Django 2.0.9 on 2018-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181101_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
